import React from 'react'
import { View, Text, StyleSheet } from '@react-pdf/renderer'

export const BRAND_PRIMARY = '#02667F'
export const BRAND_ACCENT = '#0090B7'

export const commonStyles = StyleSheet.create({
  page: {
    fontFamily: 'Helvetica',
    fontSize: 9,
    paddingTop: 36,
    paddingBottom: 36,
    paddingHorizontal: 40,
    color: '#333333',
  },
  header: {
    borderBottom: `2px solid ${BRAND_PRIMARY}`,
    paddingBottom: 10,
    marginBottom: 14,
  },
  companyName: {
    fontSize: 16,
    fontFamily: 'Helvetica-Bold',
    color: BRAND_PRIMARY,
    marginBottom: 2,
  },
  headerDetail: {
    fontSize: 8,
    color: '#666666',
    marginBottom: 1,
  },
  reportTitle: {
    fontSize: 14,
    fontFamily: 'Helvetica-Bold',
    color: BRAND_PRIMARY,
    marginBottom: 4,
  },
  reportSubtitle: {
    fontSize: 9,
    color: '#666666',
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 10,
    fontFamily: 'Helvetica-Bold',
    color: BRAND_PRIMARY,
    marginBottom: 6,
    marginTop: 10,
    textTransform: 'uppercase' as const,
  },
  tableHeader: {
    flexDirection: 'row' as const,
    backgroundColor: BRAND_PRIMARY,
    paddingVertical: 4,
    paddingHorizontal: 6,
  },
  tableHeaderText: {
    fontSize: 8,
    fontFamily: 'Helvetica-Bold',
    color: '#FFFFFF',
  },
  tableRow: {
    flexDirection: 'row' as const,
    paddingVertical: 3,
    paddingHorizontal: 6,
    borderBottom: '0.5px solid #E0E0E0',
  },
  tableRowAlt: {
    flexDirection: 'row' as const,
    paddingVertical: 3,
    paddingHorizontal: 6,
    borderBottom: '0.5px solid #E0E0E0',
    backgroundColor: '#F8F9FA',
  },
  tableFooter: {
    flexDirection: 'row' as const,
    paddingVertical: 4,
    paddingHorizontal: 6,
    backgroundColor: '#E9ECEF',
    borderTop: `1px solid ${BRAND_PRIMARY}`,
  },
  cellText: {
    fontSize: 8,
  },
  cellTextBold: {
    fontSize: 8,
    fontFamily: 'Helvetica-Bold',
  },
  cellTextMono: {
    fontSize: 8,
    fontFamily: 'Courier',
  },
  cellTextRed: {
    fontSize: 8,
    color: '#DC2626',
  },
  cellTextGreen: {
    fontSize: 8,
    color: '#16A34A',
  },
  footer: {
    position: 'absolute' as const,
    bottom: 20,
    left: 40,
    right: 40,
    fontSize: 7,
    color: '#999999',
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
  },
  summaryCard: {
    border: '1px solid #DEE2E6',
    padding: 10,
    marginBottom: 10,
  },
  summaryRow: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    paddingVertical: 2,
  },
  summaryLabel: {
    fontSize: 9,
  },
  summaryValue: {
    fontSize: 9,
    fontFamily: 'Helvetica-Bold',
  },
})

export function formatCurrency(amount: number): string {
  return `$${Math.abs(amount).toLocaleString('en-AU', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
}

export function formatDate(dateStr: string): string {
  const date = new Date(dateStr + 'T00:00:00')
  return date.toLocaleDateString('en-AU', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  })
}

interface ReportHeaderProps {
  schemeName: string
  schemeNumber: string
  schemeAddress: string
  reportTitle: string
  subtitle: string
}

export function ReportHeader({ schemeName, schemeNumber, schemeAddress, reportTitle, subtitle }: ReportHeaderProps) {
  return (
    <>
      <View style={commonStyles.header}>
        <Text style={commonStyles.companyName}>{schemeName}</Text>
        <Text style={commonStyles.headerDetail}>{schemeNumber}</Text>
        <Text style={commonStyles.headerDetail}>{schemeAddress}</Text>
      </View>
      <Text style={commonStyles.reportTitle}>{reportTitle}</Text>
      <Text style={commonStyles.reportSubtitle}>{subtitle}</Text>
    </>
  )
}

export function ReportFooter({ generatedAt }: { generatedAt: string }) {
  return (
    <View style={commonStyles.footer} fixed>
      <Text>Generated by LevyLite</Text>
      <Text>{generatedAt}</Text>
    </View>
  )
}
